### ISSUE TITLE
Black flashing, storage, and camera fading issue

### ISSUE THREAD

**Issue by whyuan1221** [Aqueti/mantis_examples#6] opened 2017-05-03 07:33 UTC
Black frames:
No matter in V1 or nous, I keep getting black frames. Sometimes the black frames are rare, but for the same render machine, the black frames will increase sometimes. 

Camera duration:
In nous, the video stream will break after about 20 minutes. I need to reopen nousviewer to retrieve the videos because some cameras just fade away.

Saving clips and play back:
When I save clip from the cameras, I can play back right after. But when I take the camera back, I can't play the clip. Map files were missing. This happened in old V1.

**Comment by camerongivler** [comment] 2017-05-03 11:47
Thanks for reporting these issues.  This is very helpful for the dev team and we will work on this.  In the future, please report separate bugs in different issues so we can assign the correct people to them and work on them separately.

**Comment by russell-taylor** [comment] 2017-05-03 16:02
Could not replicate the 20-minute camera drop using V1 on the current AGT master (49c95994ddba573be2e19e56603f31858939757c) with the current ACOS.  It ran for more than half an hour using both the previous and current acosd.  Hopefully this issue has been resolved in current code.  Nous should be checked independently.

**Comment by russell-taylor** [comment] 2017-05-03 16:05
Black frames (1): A config file that shows all of the microcameras on the same screen is known to produce black flashing from time to time.  A config file that shows the wide-FOV camera when zoomed out and only shows the narrow ones when zoomed in enough so that only half of them show on the screen at any time will fix this issue.  This has been verified on the current master.

Black frames (2): Missing frames from the microcameras are masked by V1/Nous to a certain extent in the current code base unless the '-b' option is given to V1, in which case all missing frames are displayed as black.  Verified that a non-'-b' V1 is able to run with no black frames, instead showing older frames when a frame is missing from the camera when using the current master AGT of 49c95994ddba573be2e19e56603f31858939757c

**Comment by russell-taylor** [comment] 2017-05-03 17:30
Reproduced the dropping cameras issues in a longer run, opening issue https://github.com/Aqueti/agt/issues/275 to track.

**Comment by camerongivler** [comment] 2017-05-04 11:46
Sounds like black frames are resolved.  I believe the saving clips issue is caused by not having write permission in `/etc/Aqueti`.  Have you tried running `chmod +rwx <username> /etc/Aqueti`?
Please close this issue if it is resolved.

**Comment by camerongivler** [comment] 2017-05-04 11:47
Please close if resolved

**Comment by uberferg** [comment] 2017-05-04 16:28
Cameron is right that that will cause clips not to save, but the proper directory is `/etc/aqueti` with a lowercase "a". Clips metadata is saved there to the file `/etc/aqueti/camera_CAMERAID_clips.json`, so the user running V2 needs read/write access to the folder. It may also help to just change ownership of `/etc/aqueti` to the user with `chown <username>:<username> /etc/aqueti`.

**Comment by sfeller** [comment] 2017-05-04 16:34
I am opening an internal issue to install the Aqueti directory with the correct permissions

**Closed as completed** 2017-05-05 07:10 UTC
